### ISSUE TITLE
Add a way to refresh the price

### ISSUE THREAD

**Issue by igormukhingmailcom** [Setono/SyliusShopTheLookPlugin#10]
Once user switch to another product at carousel, price should be updated.

This can be done via:
- Endpoint
- JS?

**Comment by loevgaard** [comment]
In the plugin there is no carousel, right?

**Comment by igormukhingmailcom** [comment]
Not yet, but I believe it should be there (as carousel is the best way to show the main sense of plugin at UI).

**Comment by loevgaard** [comment]
Yes, that is correct, but for now I guess we should just implement the controller that returns the price, right?
